### ISSUE TITLE
你好，请问数据增强部分的代码有涵盖在里面吗？

### ISSUE THREAD

**Issue by qiusg** [zhoujx4/NLP-Series-text-cls#1]

**Comment by zhoujx4** [comment]
有的。dataset.py里面有一个is_augement参数，使用了nlpcda库做了简单的数据增强。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/NLP-Series-text-cls"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午3:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/NLP-Series-text-cls] 你好，请问数据增强部分的代码有涵盖在里面吗？ (#1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiusg** [comment]
请问采用数据增强的话不是应该每次增强后增加一个新样例吗，但是看了你的代码好像是将原有的样例直接修改了（比如直接替换了某个词）？还有一个问题想请教一下，在长文本分类的场景下，如果采用回译法做数据增强，是应该回译其中的某些句子，还是直接回译整个文本呢？

**Comment by zhoujx4** [comment]
写在__getitem__里，每个epoch都会对句子进行修改哦 
其实在真实业务中，数据增强有两个做法：
例如你现在有5千条真实数据
做法一：基于5千条生成额外的5千条增强数据，然后你的训练集就有1万条了，这样放到模型中训练
做法二：把5千条放到模型中，在每一轮中，读取模型时，对样本进行一些增强，例如随即替换句子中某些词，或交换句子中词的位置等等

在长文本分类中，用会议的做法，我是不建议直接回译真个文本的，可能会导致回译得到的样本“面目全非”，毕竟现在翻译也不是说到很厉害的程度，最好还是从长文本中，切分句子后，选一些句子进行回译，例如一个10句话组成的长文本，随机其里面的3句做回译就行了

**Comment by qiusg** [comment]
好的，我自己再顺一顺！感谢回复！
